/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.prettybyte.simplebackend

import kotlin.test.Test

class LibraryTest {
    @Test
    fun testSomeLibraryMethod() {
        
    }
}
